const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Project = sequelize.define('Project', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  title: { type: DataTypes.STRING(300), allowNull: false },
  abstract: { type: DataTypes.TEXT, allowNull: false },
  description: { type: DataTypes.TEXT },
  province: { type: DataTypes.ENUM('Punjab','Sindh','Khyber Pakhtunkhwa','Balochistan','Gilgit-Baltistan','Azad Jammu and Kashmir','Islamabad Capital Territory'), allowNull: true, validate: { isIn: { args: [['Punjab','Sindh','Khyber Pakhtunkhwa','Balochistan','Gilgit-Baltistan','Azad Jammu and Kashmir','Islamabad Capital Territory']], msg: 'Province must be a valid Pakistani region' } } },
  primary_sector: { type: DataTypes.STRING(100), allowNull: false },
  sub_sectors: { type: DataTypes.ARRAY(DataTypes.STRING) },
  sdg_goals: { type: DataTypes.ARRAY(DataTypes.INTEGER) },
  trl_level: { type: DataTypes.INTEGER, validate: { min: 1, max: 9 } },
  status: {
    type: DataTypes.ENUM('draft','under_review','approved','rejected','changes_requested','under_implementation','completed','archived'),
    defaultValue: 'under_review'
  },
  priority_level: { type: DataTypes.ENUM('low','medium','high','critical'), defaultValue: 'medium' },
  risk_level: { type: DataTypes.ENUM('low','medium','high'), defaultValue: 'medium' },
  district: { type: DataTypes.STRING(100) },
  city: { type: DataTypes.STRING(100) },
  address: { type: DataTypes.TEXT },
  latitude: { type: DataTypes.DECIMAL(10, 8) },
  longitude: { type: DataTypes.DECIMAL(11, 8) },
  start_date: { type: DataTypes.DATEONLY },
  end_date: { type: DataTypes.DATEONLY },
  duration_months: { type: DataTypes.INTEGER },
  currency: { type: DataTypes.STRING(10), defaultValue: 'PKR' },
  total_cost: { type: DataTypes.DECIMAL(20, 2) },
  research_fund: { type: DataTypes.DECIMAL(20, 2) },
  equity_fund: { type: DataTypes.DECIMAL(20, 2) },
  debt_loan: { type: DataTypes.DECIMAL(20, 2) },
  grant_amount: { type: DataTypes.DECIMAL(20, 2) },
  funding_gap: { type: DataTypes.DECIMAL(20, 2) },
  minimum_investment: { type: DataTypes.DECIMAL(20, 2) },
  expected_roi: { type: DataTypes.DECIMAL(5, 2) },
  payback_years: { type: DataTypes.INTEGER },
  direct_beneficiaries: { type: DataTypes.INTEGER },
  indirect_beneficiaries: { type: DataTypes.INTEGER },
  jobs_created: { type: DataTypes.INTEGER },
  impact_metrics: { type: DataTypes.JSONB },
  organization_name: { type: DataTypes.STRING(200) },
  organization_type: { type: DataTypes.STRING(100) },
  organization_website: { type: DataTypes.STRING(500) },
  project_lead: { type: DataTypes.JSONB },
  team_members: { type: DataTypes.JSONB },
  shareholders: { type: DataTypes.JSONB },
  documents: { type: DataTypes.JSONB },
  videos: { type: DataTypes.JSONB },
  future_plans: { type: DataTypes.JSONB },
  tags: { type: DataTypes.ARRAY(DataTypes.STRING) },
  infographic_url: { type: DataTypes.STRING(500) },
  admin_notes: { type: DataTypes.TEXT },
  admin_feedback: { type: DataTypes.TEXT },
  reviewed_by: { type: DataTypes.UUID },
  reviewed_at: { type: DataTypes.DATE },
  views_count: { type: DataTypes.INTEGER, defaultValue: 0 },
  interests_count: { type: DataTypes.INTEGER, defaultValue: 0 },
  user_id: { type: DataTypes.UUID, allowNull: false },
}, { tableName: 'projects' });

module.exports = Project;
