import React, { useEffect, useState } from 'react';
import { analyticsAPI } from '../../services/api';
import { formatCurrency } from '../../utils/constants';

export default function ExecutiveAnalyticsPage() {
  const [portfolio, setPortfolio] = useState('wef'); const [data, setData] = useState(null);
  useEffect(() => { analyticsAPI.getPublic(portfolio).then(setData).catch(() => setData(null)); }, [portfolio]);
  const h = data?.headline || {}; const required = Number(h.total_finance_required || 0); const secured = Number(h.financing_secured || 0); const gap = Number(h.investment_gap || 0);
  const cards = [['Total Finance Required',formatCurrency(required)],['Financing Secured',formatCurrency(secured)],['Investment Gap',formatCurrency(gap)],['Total Projects',Number(h.total_projects||0).toLocaleString()],['WEF Projects',Number(h.wef_projects||0).toLocaleString()],['Provinces Covered',`${h.provinces_covered||0}/7`]];
  return <div className="min-h-screen bg-pcpp-mist"><section className="bg-pcpp-pine text-white py-12"><div className="max-w-7xl mx-auto px-4 flex flex-wrap justify-between gap-4"><div><p className="text-white/70 uppercase text-sm">Executive Dashboard</p><h1 className="text-3xl font-bold">WEF Nexus Finance & Impact</h1></div><div className="flex bg-white/10 rounded-lg p-1">{['wef','all'].map(value=><button key={value} onClick={()=>setPortfolio(value)} className={`px-4 py-2 rounded-md text-sm ${portfolio===value?'bg-white text-pcpp-pine':'text-white'}`}>{value==='wef'?'WEF Portfolio':'All Projects'}</button>)}</div></div></section><main className="max-w-7xl mx-auto px-4 py-8 space-y-7"><div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">{cards.map(([label,value])=><div key={label} className="bg-white border rounded-xl p-4"><div className="text-xs text-gray-500">{label}</div><div className="font-bold text-lg mt-1">{value}</div></div>)}</div><section className="bg-white border rounded-2xl p-6"><h2 className="font-semibold mb-4">Finance funnel</h2><div className="grid md:grid-cols-3 gap-4">{[['Required',required,'bg-pcpp-pine'],['Secured',secured,'bg-pcpp-emerald'],['Gap',gap,'bg-yellow-500']].map(([label,value,color])=><div key={label}><div className="flex justify-between text-sm mb-2"><span>{label}</span><b>{formatCurrency(value)}</b></div><div className="h-3 bg-gray-100 rounded-full"><div className={`h-3 rounded-full ${color}`} style={{width:`${required?Math.min(100,(value/required)*100):0}%`}} /></div></div>)}</div></section><div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-2xl p-6"><h2 className="font-semibold mb-4">Financing by source</h2>{(data?.funding_sources||[]).map(row=><div key={row.code} className="mb-3"><div className="flex justify-between text-sm"><span>{row.label}</span><span>{formatCurrency(row.secured)}</span></div><div className="h-2 bg-gray-100 rounded"><div className="h-2 bg-pcpp-emerald rounded" style={{width:`${Number(row.pipeline)?Math.min(100,Number(row.secured)/Number(row.pipeline)*100):0}%`}} /></div></div>)}</section><section className="bg-white border rounded-2xl p-6"><h2 className="font-semibold mb-2">Carbon Mitigation Summary</h2><div className="text-3xl font-bold text-pcpp-pine">{Number(h.total_tco2e_yr||0).toLocaleString()} <span className="text-sm font-normal">tCO₂e/year</span></div><p className="text-sm text-gray-500 mt-2">Based on projects currently reporting estimated annual reductions.</p>{(data?.carbon||[]).map(row=><div key={row.methodology} className="flex justify-between border-b py-2 text-sm"><span>{String(row.methodology).replace(/_/g,' ')}</span><span>{row.projects} projects</span></div>)}</section></div></main></div>;
}
