import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { projectsAPI } from '../../services/api';
import { formatCurrency } from '../../utils/constants';

export default function InvestPage() {
  const [projects, setProjects] = useState([]);
  useEffect(() => { projectsAPI.getAll({ priority: 'WEF', status: 'approved', limit: 100 }).then(r => setProjects(r.projects || [])).catch(() => setProjects([])); }, []);
  const sectors = useMemo(() => Object.values(projects.reduce((all, project) => { const name = project.primary_sector || 'Other'; const item = all[name] || { name, projects: 0, cost: 0, gap: 0 }; item.projects += 1; item.cost += Number(project.total_cost || 0); item.gap += Number(project.funding_gap || 0); all[name] = item; return all; }, {})), [projects]);
  const regions = new Set(projects.map(p => p.province).filter(Boolean));
  return <div className="min-h-screen bg-pcpp-mist"><section className="bg-gradient-to-br from-pcpp-pine to-pcpp-emerald text-white py-16"><div className="max-w-6xl mx-auto px-4"><p className="uppercase tracking-wider text-sm text-white/75">WEF Nexus Portfolio</p><h1 className="text-4xl font-bold mt-2">Investment → Sector → Project</h1><p className="mt-3 text-white/80">Explore approved Water, Energy and Food nexus opportunities across Pakistan.</p><div className="grid sm:grid-cols-3 gap-4 mt-8"><div className="bg-white/10 rounded-xl p-4"><b className="text-2xl">{projects.length}</b><div className="text-sm">WEF projects</div></div><div className="bg-white/10 rounded-xl p-4"><b className="text-2xl">{formatCurrency(projects.reduce((s,p)=>s+Number(p.total_cost||0),0))}</b><div className="text-sm">Finance required</div></div><div className="bg-white/10 rounded-xl p-4"><b className="text-2xl">{regions.size}/7</b><div className="text-sm">Regions covered</div></div></div></div></section><div className="max-w-6xl mx-auto px-4 py-10"><h2 className="text-2xl font-bold mb-5">Invest by sector</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{sectors.map(sector=><Link key={sector.name} to={`/invest/sector/${encodeURIComponent(sector.name)}`} className="bg-white border rounded-2xl p-5 hover:border-pcpp-emerald hover:shadow-md"><h3 className="font-semibold text-lg">{sector.name}</h3><p className="text-sm text-gray-500 mt-1">{sector.projects} projects</p><div className="mt-4 text-sm"><div>Required: <b>{formatCurrency(sector.cost)}</b></div><div>Gap: <b>{formatCurrency(sector.gap)}</b></div></div></Link>)}</div>{!sectors.length&&<p className="text-gray-500">Approved WEF projects will appear here.</p>}</div></div>;
}
